services:
  auto-booker-1:
    image: shau1943/auto-booker:latest
    restart: unless-stopped
    environment:
      - job_number=10
      - task_number=1
      - job_days=13
      - court_name=F
      - book_time=19
    volumes:
      - ./config.json:/auto-booker/config.json
  auto-booker-2:
    image: shau1943/auto-booker:latest
    restart: unless-stopped
    environment:
      - job_number=10
      - task_number=1
      - job_days=13
      - court_name=F
      - book_time=20
    volumes:
      - ./config.json:/auto-booker/config.json